FROM rust:latest AS builder

ARG COMMIT=ba1202769c6fb62ccb560bdd786598c62766dd9c

RUN apt-get update
RUN apt-get install -y clang cmake

RUN git clone https://github.com/shesek/electrs && cd electrs && git checkout ${COMMIT}

WORKDIR /electrs

RUN cargo build --features liquid --release --bin electrs

FROM debian:stable-slim

WORKDIR /build

COPY --from=builder /electrs/target/release/electrs /build

STOPSIGNAL SIGINT

ENTRYPOINT ["/build/electrs"]
