FROM rust:latest AS builder

ARG COMMIT=a808b51d0d9301fa82390b985c57551966001f9b

ENV WS_PORT=1234

RUN apt-get update
RUN apt-get install -y clang cmake

RUN git clone https://github.com/blockstream/electrs && cd electrs && git checkout ${COMMIT}

WORKDIR /electrs

RUN cargo build --features liquid --release --bin electrs

FROM debian:stable-slim AS websocat-installer

RUN apt-get update
RUN apt-get install -y wget

RUN wget https://github.com/vi/websocat/releases/download/v1.11.0/websocat.x86_64-unknown-linux-musl \
    && chmod +x websocat.x86_64-unknown-linux-musl \
    && mv websocat.x86_64-unknown-linux-musl /usr/local/bin/websocat

FROM debian:stable-slim

WORKDIR /build

COPY --from=builder /electrs/target/release/electrs /usr/local/bin
COPY --from=websocat-installer /usr/local/bin/websocat /usr/local/bin

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

STOPSIGNAL SIGINT

ENTRYPOINT /entrypoint.sh ${WS_PORT}
