FROM rust:latest AS builder

ARG COMMIT=a808b51d0d9301fa82390b985c57551966001f9b

RUN apt-get update
RUN apt-get install -y clang cmake

RUN git clone https://github.com/blockstream/electrs && cd electrs && git checkout ${COMMIT}

WORKDIR /electrs

RUN cargo build --features liquid --release --bin electrs

FROM debian:stable-slim AS websocat-installer

RUN apt-get update
RUN apt-get install -y wget

COPY install-websocat.sh /install-websocat.sh
RUN chmod +x /install-websocat.sh && /install-websocat.sh

FROM debian:stable-slim

WORKDIR /build

COPY --from=builder /electrs/target/release/electrs /usr/local/bin
COPY --from=websocat-installer /usr/local/bin/websocat /usr/local/bin

STOPSIGNAL SIGINT

ENTRYPOINT ["bash", "/entrypoint.sh"]
